### PR TITLE
Add `keep-tags` multi-line input

### LINKED ISSUE #9: Allow for excluded tag when using tag-regex
I want to use this to remove images created during pull requests, however, sometimes some of the images may receive additional tags, if a team member needs to use a specific version for some tests. 

If one could add an exclusion either regex, or fixed tag, then one could instead of saying keep latest say exclude: 'stable' for example.

I've not looked at the code at all, so I'm not sure what this would take, but If my thinking is right, a list is generated of images with tags to be removed. Then one could simply apply a second filter excluding those that need to be excluded.

Alternatively, and I haven't tested this, will an image with multiple tags be pruned by default? If that approach were followed, the matching tags could be removed, and then all untagged could be removed.

### PR DESCRIPTION
**Pull request by vlaurin**
Resolves #9
Ability to exclude versions from pruning by exactly matching at least one tag to keep.

### CODE REVIEW

**Comment by vlaurin** [comment]
@FlippievanDyk here you go, this is adding both `keep-tags` and `keep-tags-regexes` as multi-line inputs.

Do you want to give it a spin? It got tested as part of the workflow on this PR but outside of that I don't have a use-case for it myself.

You should be able to use it by referencing this branch directly, like so:

```yml
steps:
  - name: Prune
    uses: vlaurin/action-ghcr-prune@9-keep-tags
    with:
      token: ${{ secrets.YOUR_TOKEN }}
      organization: your-org
      container: your-container
      dry-run: true # Dry-run first, then change to `false`
      tag-regex: your-regex
      keep-tags: |
        first-tag
        second-tag
```

For more details, feel free to have a look at the changes to the `README` and `action.yml` on this PR. If you are happy with it, I'll release it next.

**Comment by FlippievanDyk** [comment]
> Do you want to give it a spin? It got tested as part of the workflow on this PR but outside of that I don't have a use-case for it myself.

Awesome! I will try to test it out in this week, and I 'll give feedback as soon as that's done.

**Comment by FlippievanDyk** [comment]
Finally got around to testing this. 

I don't have a use for keep tags-regex at the moment, but keep-tags works perfectly! 

Thank you so much for this, it is exactly what I was after.

**Comment by vlaurin** [comment]
@FlippievanDyk great, thank you for giving it a spin, I'm going to release it now :)

**Pull request merged**
